integrate Liger into training
MeetKai/functionary pull request #275
Opened 2024-10-18 04:24 UTC by khai-meetkai

+ integrate https://github.com/linkedin/Liger-Kernel into training, this can reduce the memory and speed.

2024-10-25 03:53 UTC, jeffrey-fong requested changes
Non-approval before I test liger with LoRA

2024-10-25 03:53 UTC, jeffrey-fong commented on functionary/train/train_lora.py
> +        default=False, metadata={"help": "Whether use liger or not"}
Add Triton supported hardware here for users to be informed of this restriction. [https://github.com/triton-lang/triton?tab=readme-ov-file#compatibility](https://github.com/triton-lang/triton?tab=readme-ov-file#compatibility)

2024-10-25 03:54 UTC, jeffreymeetkai requested changes
^

2024-10-28 03:30 UTC, jeffreymeetkai approved these changes

2024-10-28 03:51 UTC, merged