Add Dockerfile
MeetKai/functionary pull request #278
Opened 2024-10-22 16:11 UTC by nvonpentz

Resolves https://github.com/MeetKai/functionary/issues/276

2024-10-30 08:30 UTC, jeffreymeetkai requested changes

2024-10-30 08:30 UTC, jeffreymeetkai commented on Dockerfile
> +    python3 -m pip install -r requirements.txt
Can you change the dependency installation to follow the instructions in this [branch](https://github.com/MeetKai/functionary/tree/sglang?tab=readme-ov-file#installation)?

2024-10-30 08:30 UTC, jeffreymeetkai commented on Dockerfile
> +ENTRYPOINT ["python3", "server_vllm.py", "--model", "meetkai/functionary-small-v3.2", "--host", "0.0.0.0", "--max-model-len", "8192"]
Can we allow user-defined options at container runtime? Maybe something like `CMD []`

2024-10-30 08:30 UTC, jeffreymeetkai commented on Dockerfile
> +WORKDIR /workspace
Can we allow user-defined workdir? Maybe we can default to `/workspace` if none is provided.

2024-11-06 00:34 UTC, jeffreymeetkai commented on Dockerfile
> +    python3 -m pip install -r requirements.txt
I will merge that branch before this so you can install following the instructions from [that branch](https://github.com/MeetKai/functionary/tree/sglang?tab=readme-ov-file#installation).

2024-11-06 02:26 UTC, jeffreymeetkai commented on Dockerfile
> +    python3 -m pip install -r requirements.txt
That branch has just been merged to main.

2024-12-02 17:57 UTC, nachthammer commented
Any progress here? Would be nice to have a docker deployment option for vllm @jeffreymeetkai 
I mean if the dockerfiles need some user defined attributes, the user can change it themselves when cloning this repository. And otherwise just having a Dockerfile here even if it is per default not super customizable would be very wild.

2024-12-20 14:06 UTC, nvonpentz commented
It's been ready for another review from @jeffreymeetkai, though it's possible it's gone stale since it's been a little while

2025-01-13 07:15 UTC, jeffreymeetkai reviewed
Sorry for getting back really late. LGTM, just that I've moved the file into the dockerfiles directory to consolidate all the dockerfiles together. Will merge after the tests are passed. Thanks for this PR!

2025-01-13 07:16 UTC, jeffreymeetkai approved these changes

2025-01-13 07:16 UTC, merged