Integrate new prompt mechanism into training
MeetKai/functionary pull request #40
Opened 2023-10-03 05:06 UTC by jeffreymeetkai

- move train.py to root folder
- implement token and embedding resizing to add the new tokens
- fix compute_metrics to use `len(tokenizer)` instead of `tokenizer.vocab_size` when reshaping the tensors/arrays
- integrate prepare_training_inputs into CustomDataset class

2023-10-03 08:10 UTC, musab-mk requested changes

2023-10-03 08:10 UTC, musab-mk commented on train.py
> +from train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
Transformers must be imported after the patch. Lets revert back the previous order

2023-10-03 08:10 UTC, musab-mk commented on train.py
> +    )
I think we should refactor tokenizer initialization into seperate function

2023-10-03 08:10 UTC, musab-mk commented on train/custom_datasets.py
> +        + "\nsystem:\nA chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. The assistant calls fu
We should let the get_prompt_from_messages function to prepare the input. So, prepend this as a message dict to the original messages.

2023-10-03 08:10 UTC, musab-mk commented on train/custom_datasets.py
> +        + "\nsystem:\nA chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. The assistant calls fu
with proper role and content etc

2023-10-03 08:10 UTC, musab-mk commented on train/custom_datasets.py
> +    messages: List[Dict],
are you sure this is a list?

2023-10-03 08:10 UTC, musab-mk commented on train/custom_datasets.py
> +    messages: List[Dict],
Maybe we should add some CI action to catch these kind of stuff

2023-10-03 08:10 UTC, musab-mk commented on train/custom_datasets.py
> +            "input_ids": ret[1]["input_ids"],
Why is this ret[1] ? Can we find a more explicit way. If we cannot, we should at least add some clarification

2023-10-04 06:55 UTC, musab-mk requested changes

2023-10-04 06:55 UTC, musab-mk commented on functionary/train/custom_datasets.py
Can we rename this file into something much more appropriate

2023-10-04 06:55 UTC, musab-mk commented on functionary/train/custom_datasets.py
In general, let's spend more time on naming things

2023-10-04 06:55 UTC, musab-mk commented on functionary/prompt.py
> +SYSTEM_MESSAGE = """A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. The assistant calls func
There was already a system message in the inference. Either let's delete this and import that one. Or delete the other one.

2023-10-04 08:03 UTC, jeffreymeetkai commented on tests/test_prompt_creation.py
> +            "musabgultekin/functionary-7b-v1", legacy=True
I've set both to using fast tokenizer with legacy=True.

2023-10-04 08:04 UTC, jeffreymeetkai commented on tests/test_prompt_creation.py
> +            final_prompt.strip(),
Fixed

2023-10-04 08:38 UTC, musab-mk approved these changes

2023-10-04 08:38 UTC, merged